export const categoriesData = [
  {
    name: 'Technology',
    slug: 'technology',
    subtitle: 'Web & Custom Solutions',
    description: 'High-performance web architecture, bespoke business applications, API engines, and intelligent automation systems engineered for mission-critical scale.',
    icon: 'Terminal',
    order: 1,
  },
  {
    name: 'Creative',
    slug: 'creative',
    subtitle: 'Design & Brand Identity',
    description: 'Timeless visual identities, editorial design systems, brand guidelines, and high-impact marketing collateral for market leaders.',
    icon: 'Palette',
    order: 2,
  },
  {
    name: 'Digital',
    slug: 'digital',
    subtitle: 'Business & Digital Solutions',
    description: 'Practical digital presence tools, conversational automation, workflow digitization, and operational document systems.',
    icon: 'Sparkles',
    order: 3,
  },
];

// Helper to generate full service details
const createServiceObj = (name, slug, category, shortDesc, fullDesc, icon, deliverables, idealFor, process, faq, order) => ({
  name,
  slug,
  category,
  shortDescription: shortDesc,
  description: fullDesc,
  icon,
  deliverables,
  idealFor,
  process: process || [
    { step: 1, title: 'Discovery & Scope', description: 'Deep technical analysis of current architecture and requirements.' },
    { step: 2, title: 'Architecture & Design', description: 'Specification of system interfaces, components, and data structures.' },
    { step: 3, title: 'Development & Testing', description: 'Iterative, type-safe implementation with continuous validation.' },
    { step: 4, title: 'Deployment & Evolution', description: 'Zero-downtime release, performance monitoring, and ongoing optimization.' },
  ],
  faq: faq || [
    { question: 'What is the standard turnaround time?', answer: 'Project timelines range from 1 to 4 weeks depending on scope, technical complexity, and review cycles.' },
    { question: 'Do you provide continuous maintenance after launch?', answer: 'Yes, we offer dedicated Service Level Agreements (SLAs) with monitoring, security patches, and iterative improvements.' },
    { question: 'How is intellectual property handled?', answer: 'Full intellectual property and code ownership are transferred directly to your organization upon project completion.' },
  ],
  order,
  published: true,
});

export const servicesData = [
  // 1. TECHNOLOGY SERVICES
  createServiceObj(
    'Web Development',
    'web-development',
    'technology',
    'Modern, lightning-fast web applications built on reactive architectures and scalable cloud backends.',
    'We engineer custom web platforms tailored specifically to your organization’s operational flows. From robust architectural design to performant frontends, our solutions emphasize security, extreme responsiveness, and clean codebases.',
    'Code',
    ['Custom React/Vite Frontend', 'Scalable REST/GraphQL API', 'Database Architecture', 'Automated CI/CD Pipeline', 'Full Source Code & Documentation'],
    ['Growing enterprises requiring custom software', 'Startups launching core products', 'Organizations upgrading legacy web systems'],
    null,
    null,
    1
  ),
  createServiceObj(
    'Business Websites',
    'business-websites',
    'technology',
    'High-converting, editorial-grade corporate websites that communicate authority and trust.',
    'Your corporate website is the digital headquarters of your business. We craft bespoke, typography-focused digital experiences that articulate your value proposition and drive enterprise inquiries.',
    'Globe',
    ['Custom Design System', 'CMS Integration', 'Enterprise SEO Setup', 'Responsive Mobile Optimization', 'Speed & Security Hardening'],
    ['B2B Corporations', 'Consultancies & Professional Firms', 'Technology Ventures'],
    null,
    null,
    2
  ),
  createServiceObj(
    'Landing Pages',
    'landing-pages',
    'technology',
    'Precision-engineered, single-purpose landing pages optimized for maximum conversion velocity.',
    'High-stakes product launches and marketing campaigns demand razor-sharp landing pages with sub-second load times, compelling visual hierarchy, and frictionless interaction flows.',
    'Layout',
    ['Conversion Architecture', 'Micro-Interactions & Motion', 'A/B Testing Readiness', 'Analytics & Pixel Integration'],
    ['Product Launches', 'Marketing Campaigns', 'Early Access Waitlists'],
    null,
    null,
    3
  ),
  createServiceObj(
    'Portfolio Websites',
    'portfolio-websites',
    'technology',
    'Curated digital portfolios designed for executives, creative directors, and specialized agencies.',
    'Showcase high-impact casework, credentials, and achievements with sophisticated editorial layouts, smooth transitions, and tactile digital finesse.',
    'Briefcase',
    ['Interactive Project Showcase', 'Media Optimization', 'Contact Gateway', 'Personal Brand Strategy'],
    ['Executives & Founders', 'Design Studios', 'Architects & Consultants'],
    null,
    null,
    4
  ),
  createServiceObj(
    'E-commerce Websites',
    'ecommerce-websites',
    'technology',
    'Bespoke digital storefronts with frictionless checkout, inventory syncing, and global payments.',
    'We build tailored e-commerce platforms engineered for fast catalog browsing, robust cart mechanics, and seamless payment gateway integrations.',
    'ShoppingBag',
    ['Custom Product Catalog', 'Stripe/Payment Gateway Integration', 'Order Management Backend', 'Inventory Synchronization'],
    ['Direct-to-Consumer Brands', 'B2B Wholesale Platforms', 'Boutique Retailers'],
    null,
    null,
    5
  ),
  createServiceObj(
    'Web Applications',
    'web-applications',
    'technology',
    'Complex cloud-native web applications with real-time state synchronization and multi-tenant architectures.',
    'From SaaS platforms to collaborative tools, our web applications leverage modern JavaScript runtimes, robust API gateways, and scalable database schemas.',
    'AppWindow',
    ['Role-Based Access Control', 'State Management Architecture', 'Real-time WebSocket/Polling', 'Cloud Deployment'],
    ['SaaS Companies', 'Product Teams', 'Internal Innovation Labs'],
    null,
    null,
    6
  ),
  createServiceObj(
    'Admin Dashboards',
    'admin-dashboards',
    'technology',
    'Intelligent back-office control panels, telemetry monitoring, and data management suites.',
    'Transform complex operational data into actionable clarity with clean charts, granular permissions, bulk actions, and instant audit trails.',
    'BarChart2',
    ['Interactive Charting Systems', 'Data Table Filtering & Export', 'User & Permission Management', 'Activity Logs'],
    ['Operations Managers', 'Platform Administrators', 'Data Teams'],
    null,
    null,
    7
  ),
  createServiceObj(
    'Website Maintenance',
    'website-maintenance',
    'technology',
    'Proactive uptime monitoring, security patching, dependency upgrades, and performance tuning.',
    'Protect your digital assets with continuous technical maintenance, automated backups, vulnerability audits, and ongoing SLA-backed support.',
    'ShieldCheck',
    ['Weekly Security Audits', 'Automated Daily Backups', 'Performance Regression Checks', 'Priority Issue Resolution'],
    ['Enterprises with high traffic', 'Mission-critical web portals', 'E-commerce operators'],
    null,
    null,
    8
  ),
  createServiceObj(
    'Custom Web Applications',
    'custom-web-applications',
    'technology',
    'End-to-end bespoke software built from the ground up to solve singular organizational challenges.',
    'When off-the-shelf software fails to match your exact workflows, we develop custom web software engineered around your precise operational requirements.',
    'Cpu',
    ['Custom Domain Logic Engine', 'Tailored Data Schemas', 'Integrations with Legacy Systems', 'Scalable Cloud Infrastructure'],
    ['Specialized Industry Verticals', 'Proprietary Workflow Operations', 'High-Growth Tech Firms'],
    null,
    null,
    9
  ),
  createServiceObj(
    'Business Management Systems',
    'business-management-systems',
    'technology',
    'Centralized platforms for resource planning, inventory tracking, client lifecycles, and internal ops.',
    'Unify fragmented departmental spreadsheets into a single, synchronized platform that provides real-time visibility into every facet of your business.',
    'Server',
    ['ERP / CRM Modules', 'Inventory & Pipeline Tracking', 'Automated Invoicing', 'Unified Reporting'],
    ['Mid-sized Enterprises', 'Logistics & Supply Firms', 'Service Agencies'],
    null,
    null,
    10
  ),
  createServiceObj(
    'Internal Business Tools',
    'internal-business-tools',
    'technology',
    'Tailored internal portals and workflow accelerators that eliminate repetitive manual labor.',
    'Empower your internal teams with high-speed internal utilities designed for rapid data processing, verification, and automated team handoffs.',
    'Sliders',
    ['Custom Admin Tools', 'Batch Data Processors', 'Team Approval Gateways', 'Slack/Email Integrations'],
    ['Internal Ops Teams', 'Customer Support Departments', 'Finance & Billing Teams'],
    null,
    null,
    11
  ),
  createServiceObj(
    'Automation Solutions',
    'automation-solutions',
    'technology',
    'Algorithmic webhooks, multi-step workflow pipelines, and background job processing.',
    'Connect disparate software platforms and trigger automated actions based on real-time business events, saving hundreds of engineering and operational hours.',
    'Workflow',
    ['Webhook Integration Frameworks', 'Scheduled Cron Pipelines', 'Error Handling & Alerting', 'Cross-platform Syncing'],
    ['Fast-scaling Teams', 'Operations Specialists', 'Data-intensive Businesses'],
    null,
    null,
    12
  ),
  createServiceObj(
    'Database Solutions',
    'database-solutions',
    'technology',
    'Database schema design, indexing strategies, query optimization, and secure data storage.',
    'Design resilient document and relational data architectures that guarantee low query latency, strict consistency, and reliable backup replication.',
    'Database',
    ['Schema Modeling & Indexing', 'Migration Scripts', 'High-availability Replication Setup', 'Query Tuning & Benchmarking'],
    ['Data-heavy Applications', 'Platforms experiencing latency', 'Firms scaling user bases'],
    null,
    null,
    13
  ),
  createServiceObj(
    'API Integration',
    'api-integration',
    'technology',
    'Seamless connection with third-party payment gateways, CRM systems, AI endpoints, and ERPs.',
    'Bridge your digital ecosystem with robust, fault-tolerant API connectors featuring automatic retries, rate limiting, and encrypted payload handling.',
    'Network',
    ['RESTful & GraphQL Connectors', 'OAuth / Token Authentication', 'Payload Validation & Mapping', 'Monitoring & Failure Alerts'],
    ['Enterprises consolidating tools', 'Fintech & Payment Applications', 'AI-augmented platforms'],
    null,
    null,
    14
  ),
  createServiceObj(
    'Custom Technology Solutions',
    'custom-technology-solutions',
    'technology',
    'R&D and bespoke technical architectures designed for uncharted business models.',
    'Partner directly with our senior technology strategists to blueprint, prototype, and build proprietary digital assets that deliver definitive market advantages.',
    'Compass',
    ['Technical Feasibility Studies', 'Proof of Concept (PoC) Builds', 'System Architecture Blueprints', 'Production Deployment Roadmap'],
    ['Executive Innovators', 'Venture Builders', 'Pioneering Tech Companies'],
    null,
    null,
    15
  ),

  // 2. CREATIVE SERVICES
  createServiceObj(
    'Graphic Design',
    'graphic-design',
    'creative',
    'High-end visual communication that elevates your brand perception and market presence.',
    'Sophisticated visual compositions that synthesize typography, geometry, and editorial hierarchy to establish a distinct, memorable aesthetic.',
    'PenTool',
    ['Vector Graphics', 'Editorial Assets', 'Digital Layouts', 'Print-Ready Formats'],
    ['Brands seeking premium positioning', 'Marketing Teams', 'Publishers'],
    null,
    null,
    16
  ),
  createServiceObj(
    'Logo Design',
    'logo-design',
    'creative',
    'Distinctive, minimalist, and timeless logomarks crafted for longevity and scalability.',
    'An iconic mark that encapsulates your organization’s core vision across digital icons, architecture, and luxury print media.',
    'Feather',
    ['Primary Logomark & Wordmark', 'Monogram & Icon Variations', 'Vector Source Files (SVG, EPS, AI)', 'Clear Space & Usage Rules'],
    ['New Ventures', 'Rebranding Enterprises', 'Funded Startups'],
    null,
    null,
    17
  ),
  createServiceObj(
    'Poster Design',
    'poster-design',
    'creative',
    'Editorial, typographic posters designed for flagship announcements and summits.',
    'Combine large-format visual drama with structured informational layout for architectural exhibitions, product launches, and digital events.',
    'Image',
    ['High-Resolution Print Files', 'Digital Display Adaptations', 'Art Direction Blueprint'],
    ['Event Organizers', 'Cultural & Tech Summits', 'Product Launch Campaigns'],
    null,
    null,
    18
  ),
  createServiceObj(
    'Banner Design',
    'banner-design',
    'creative',
    'Targeted digital display banners and trade show backdrops designed for brand recall.',
    'High-impact banners engineered with clear visual hierarchy, striking color balances, and concise messaging.',
    'Maximize',
    ['Web Display Banners', 'Exhibition / Roll-Up Graphics', 'Multi-ratio Export Packs'],
    ['Conference Exhibitors', 'Digital Marketers', 'Product Promoters'],
    null,
    null,
    19
  ),
  createServiceObj(
    'Flyer Design',
    'flyer-design',
    'creative',
    'Premium single and multi-page flyers that communicate key offerings with clarity.',
    'Clean, structured physical and digital flyers that capture immediate attention and encourage clear action.',
    'FileText',
    ['Print-Ready CMYK Files', 'Web-Optimized PDFs', 'Editable Source Layouts'],
    ['Local Business Launches', 'Corporate Events', 'Direct Sales Outreach'],
    null,
    null,
    20
  ),
  createServiceObj(
    'Brochure Design',
    'brochure-design',
    'creative',
    'Comprehensive multi-fold and booklet brochures with editorial typography.',
    'Showcase your complete product suite or corporate services in an elegant, structured format built for client meetings and executive presentations.',
    'BookOpen',
    ['Tri-fold, Bi-fold, or Multi-page Layouts', 'Print Production Specifications', 'Interactive Digital Version'],
    ['Enterprise Sales Teams', 'Real Estate & Luxury Brands', 'Consulting Firms'],
    null,
    null,
    21
  ),
  createServiceObj(
    'Business Card Design',
    'business-card-design',
    'creative',
    'Minimalist, tactile business cards featuring bespoke typography and premium finishes.',
    'Create an indelible first impression with refined typography, foil stamping guides, and spot UV specifications.',
    'CreditCard',
    ['Vector Print Layouts', 'Finishing & Foil Guides', 'Employee Template System'],
    ['Founders & Executives', 'Client Relationship Teams', 'Creative Professionals'],
    null,
    null,
    22
  ),
  createServiceObj(
    'Catalogue Design',
    'catalogue-design',
    'creative',
    'Structured product and collection catalogues engineered for effortless browsing.',
    'Harmonious grid systems and high-legibility typographic hierarchies that present extensive product catalogs with editorial prestige.',
    'Grid',
    ['Master Grid Template', 'Index & Table of Contents', 'Print & Digital Versions', 'Asset Export Guide'],
    ['Manufacturers', 'Product Studios', 'Architectural Suppliers'],
    null,
    null,
    23
  ),
  createServiceObj(
    'Social Media Creatives',
    'social-media-creatives',
    'creative',
    'Cohesive social content templates and carousels aligned with your brand aesthetics.',
    'Stand out across social feeds with consistent, high-taste visual assets and editorial carousels that drive engagement.',
    'Share2',
    ['Figma/Canva Template System', 'Feed & Story Multi-size Assets', 'Typographic Hierarchy Guide'],
    ['Social Media Managers', 'Brand Marketers', 'Founders building in public'],
    null,
    null,
    24
  ),
  createServiceObj(
    'Marketing Materials',
    'marketing-materials',
    'creative',
    'Holistic marketing suites including pitch decks, one-pagers, and campaign collateral.',
    'Equip your sales and growth teams with polished visual materials that accelerate deal cycles and impress stakeholders.',
    'Target',
    ['Pitch Deck Design', 'Executive One-Pagers', 'Case Study Templates', 'Campaign Visuals'],
    ['Sales Enablement Teams', 'Founders Pitching Investors', 'Corporate Communications'],
    null,
    null,
    25
  ),
  createServiceObj(
    'Event & Invitation Design',
    'event-and-invitation-design',
    'creative',
    'Exclusive physical and digital invitations for VIP summits, dinners, and gatherings.',
    'Set the tone for your most prestigious events with curated typography, custom envelopes, and digital RSVP portals.',
    'Calendar',
    ['Digital RSVP Assets', 'Printed Invitation Cards', 'Event Signage Guidelines'],
    ['Private Equity & Venture Hosts', 'Corporate Gala Organizers', 'Exclusive Product Showcases'],
    null,
    null,
    26
  ),
  createServiceObj(
    'Branding',
    'branding',
    'creative',
    'Comprehensive brand development from strategic positioning to multi-channel execution.',
    'We construct foundational brand identities that establish authority, differentiate from competitors, and resonate deeply with target demographics.',
    'Layers',
    ['Brand Positioning Strategy', 'Visual Identity Architecture', 'Brand Tone of Voice', 'Asset Library'],
    ['New Corporate Entities', 'Venture-backed Startups', 'Companies Pivoting Markets'],
    null,
    null,
    27
  ),
  createServiceObj(
    'Brand Identity',
    'brand-identity',
    'creative',
    'Full visual design systems comprising color palettes, typography, imagery rules, and icon sets.',
    'A unified visual language ensuring flawless consistency across every digital and physical touchpoint.',
    'Eye',
    ['Color Palette Specification', 'Typography Pairings', 'Iconography System', 'Component Guidelines'],
    ['Product Teams', 'Marketing Departments', 'Global Brands'],
    null,
    null,
    28
  ),
  createServiceObj(
    'Brand Guidelines',
    'brand-guidelines',
    'creative',
    'Comprehensive brand bible and design token specifications for internal and partner teams.',
    'An exhaustive digital and PDF handbook documenting exact rules for logos, spacing, color contrast, and voice.',
    'Bookmark',
    ['Brand Bible PDF', 'Design Token JSON/CSS', 'Do’s & Don’ts Showcase', 'Asset Download Links'],
    ['Enterprise Design Teams', 'Agencies handing off to clients', 'Distributed Organizations'],
    null,
    null,
    29
  ),
  createServiceObj(
    'Letterhead Design',
    'letterhead-design',
    'creative',
    'Refined corporate letterheads for formal correspondence and legal documentation.',
    'Ensure all written corporate communications project professionalism and precision.',
    'File',
    ['Word & Google Docs Templates', 'Vector Print Master', 'Digital Header/Footer Specs'],
    ['Legal & Advisory Firms', 'Corporate Executives', 'Financial Institutions'],
    null,
    null,
    30
  ),
  createServiceObj(
    'Invoice Design',
    'invoice-design',
    'creative',
    'Clean, branded invoice and estimate templates tailored for billing workflows.',
    'Transform everyday accounting touchpoints into sleek extensions of your brand identity.',
    'Receipt',
    ['PDF Invoice Template', 'Dynamic Spreadsheet Template', 'Email Receipt Styling'],
    ['Agencies & Consultancies', 'B2B Vendors', 'Freelance Collaborators'],
    null,
    null,
    31
  ),
  createServiceObj(
    'Company Profile Design',
    'company-profile-design',
    'creative',
    'Authoritative corporate profiles detailing history, team, capabilities, and achievements.',
    'A premier multi-page document tailored for enterprise RFP submissions, joint venture proposals, and investor packages.',
    'Award',
    ['Multi-page Corporate Deck', 'Interactive Web PDF', 'Editable Source Files'],
    ['Firms responding to RFPs', 'Enterprises seeking international partners', 'Investor Relations'],
    null,
    null,
    32
  ),
  createServiceObj(
    'Business Stationery',
    'business-stationery',
    'creative',
    'Complete stationery suites including folders, envelopes, notepads, and badges.',
    'A fully synchronized physical collateral suite that showcases meticulous attention to detail in every executive meeting.',
    'Folder',
    ['Presentation Folder Layout', 'Envelopes (Standard & Window)', 'Notepad & Pen Branding', 'Event Badges'],
    ['Corporate Headquarters', 'High-end Hospitality', 'Professional Services'],
    null,
    null,
    33
  ),

  // 3. DIGITAL SERVICES
  createServiceObj(
    'WhatsApp Business Setup',
    'whatsapp-business-setup',
    'digital',
    'Verified WhatsApp Business API integration, catalog setup, automated greetings, and CRM linking.',
    'Transform the world’s most popular messaging platform into a direct, automated customer acquisition and support channel.',
    'MessageSquare',
    ['WhatsApp Business API Verification', 'Product Catalog Upload', 'Automated Quick Replies & Greetings', 'CRM Webhook Integration'],
    ['Direct-to-consumer businesses', 'Service providers with high customer volume', 'International vendors'],
    null,
    null,
    34
  ),
  createServiceObj(
    'Digital Business Cards',
    'digital-business-cards',
    'digital',
    'Interactive NFC and QR-enabled digital business cards that save directly to mobile phone contacts.',
    'Share your full professional profile, portfolio, and contact details with a single tap or scan on any smartphone.',
    'Smartphone',
    ['vCard Mobile Profile', 'NFC Hardware Compatibility', 'Custom Branded QR Link', 'Real-time Link Updating'],
    ['Sales Executives', 'Networking Professionals', 'Conference Attendees'],
    null,
    null,
    35
  ),
  createServiceObj(
    'QR Code Solutions',
    'qr-code-solutions',
    'digital',
    'Dynamic, branded QR codes with real-time redirect capabilities and scan analytics.',
    'Never print a static, unchangeable QR code again. Update the destination URL at any time and monitor scan location and frequency.',
    'QrCode',
    ['Custom Vector QR Design', 'Dynamic URL Routing Engine', 'Scan Analytics Dashboard', 'High-res Vector Exports'],
    ['Restaurants & Retailers', 'Event Marketers', 'Packaging Designers'],
    null,
    null,
    36
  ),
  createServiceObj(
    'Digital Menus',
    'digital-menus',
    'digital',
    'Interactive, mobile-first digital menus for restaurants, cafes, and hospitality venues.',
    'Provide patrons with instant menu access, item filtering, multilingual translations, and rich imagery without requiring app downloads.',
    'Coffee',
    ['Mobile-optimized Web Menu', 'Category & Allergen Filters', 'Instant Price & Item Updates', 'Table QR Generator'],
    ['Restaurants & Bars', 'Hotel Room Service', 'Specialty Cafes'],
    null,
    null,
    37
  ),
  createServiceObj(
    'Online Forms',
    'online-forms',
    'digital',
    'Multi-step intake forms, applicant portals, and feedback surveys with automated email notifications.',
    'Collect validated data efficiently with logic branching, file upload capabilities, and instant sync to Google Sheets, Notion, or databases.',
    'CheckSquare',
    ['Conditional Logic Branching', 'File Upload Handling', 'Auto-responder Notifications', 'Spreadsheet / Webhook Sync'],
    ['Human Resources', 'Client Onboarding Teams', 'Research & Survey Conductors'],
    null,
    null,
    38
  ),
  createServiceObj(
    'Digital Business Presence',
    'digital-business-presence',
    'digital',
    'Complete setup across Google Business Profile, Apple Maps, local directories, and search indexes.',
    'Ensure your business is discoverable, accurately located, and properly verified across all major search engines and mapping ecosystems.',
    'MapPin',
    ['Google Business Verification & Optimization', 'Apple Maps Business Connect', 'Local Schema Markup', 'Review Strategy Guide'],
    ['Local Commercial Entities', 'Multi-location Businesses', 'New Retail Venues'],
    null,
    null,
    39
  ),
  createServiceObj(
    'Digital Setup & Support',
    'digital-setup-and-support',
    'digital',
    'Corporate domain configuration, business email setup (Google Workspace / M365), DNS, and SSL security.',
    'Establish a rock-solid, professional digital foundation with authenticated email routing (DKIM/SPF/DMARC) and zero deliverability issues.',
    'Settings',
    ['Google Workspace / M365 Setup', 'SPF, DKIM, DMARC Configuration', 'Custom Domain DNS Routing', 'SSL Encryption Installation'],
    ['New Businesses & Founders', 'Companies moving domains', 'Teams facing email spam issues'],
    null,
    null,
    40
  ),
  createServiceObj(
    'Resume / CV Creation',
    'resume-cv-creation',
    'digital',
    'Executive resumes and modern CVs formatted for ATS parsers and executive search committees.',
    'Present your career trajectory with crisp typography, quantified impact metrics, and flawless applicant tracking system compatibility.',
    'UserCheck',
    ['ATS-Optimized PDF & Word Master', 'Executive Bio Summary', 'LinkedIn Profile Alignment'],
    ['C-Suite Executives', 'Senior Software Engineers', 'Industry Specialists'],
    null,
    null,
    41
  ),
  createServiceObj(
    'PDF Creation',
    'pdf-creation',
    'digital',
    'Interactive, fillable, and digitally signable PDF documents engineered to corporate specifications.',
    'Transform static forms into interactive digital PDFs with calculations, required fields, and digital signature blocks.',
    'FilePlus',
    ['Fillable Form Fields', 'Embedded Calculations', 'Interactive Buttons & Bookmarks', 'Print/Screen Optimization'],
    ['Legal Departments', 'Insurance & Finance Agencies', 'Administrative Teams'],
    null,
    null,
    42
  ),
  createServiceObj(
    'PDF Editing',
    'pdf-editing',
    'digital',
    'Text corrections, layout adjustments, page reorganizations, and optimization of legacy PDF files.',
    'Rapid updates and clean adjustments to existing PDF collateral without requiring original design files.',
    'Edit3',
    ['Text & Image Replacements', 'Page Extraction & Merging', 'File Size Compression', 'OCR Text Recognition'],
    ['Operations Teams', 'Office Administrators', 'Academic & Publishing Teams'],
    null,
    null,
    43
  ),
  createServiceObj(
    'Document Formatting',
    'document-formatting',
    'digital',
    'Standardization of technical manuals, whitepapers, and operational handbooks.',
    'Transform unformatted drafts into beautiful, consistent documents adhering to strict typographical standards.',
    'AlignLeft',
    ['Header/Footer Numbering Schemes', 'Table of Contents & Cross-references', 'Standardized Font & Color Hierarchy', 'Clean Export Packs'],
    ['Research Organizations', 'Technical Writers', 'Compliance Officers'],
    null,
    null,
    44
  ),
  createServiceObj(
    'Excel Work',
    'excel-work',
    'digital',
    'Advanced spreadsheet modeling, dynamic lookup formulas, automated macros, and pivot dashboards.',
    'Convert raw tabular figures into intuitive financial models, automated reporting calculators, and executive spreadsheets.',
    'Table',
    ['Financial Modeling Spreadsheets', 'VLOOKUP / XLOOKUP / INDEX-MATCH Formulations', 'Automated VBA/Apps Scripts', 'Visual Data Summaries'],
    ['Finance Teams', 'Sales Forecasting Units', 'Inventory Controllers'],
    null,
    null,
    45
  ),
  createServiceObj(
    'Data Entry',
    'data-entry',
    'digital',
    'Accurate, structured digitization and normalization of legacy records and physical paperwork.',
    'High-fidelity data transfer into digital databases and spreadsheets with thorough verification protocols.',
    'Database',
    ['Data Cleaning & Deduplication', 'Validation Rules Application', 'CSV / JSON / SQL Export Format', 'Error Auditing Report'],
    ['Companies digitizing paper records', 'E-commerce store managers', 'Researchers'],
    null,
    null,
    46
  ),
  createServiceObj(
    'Digital Documentation',
    'digital-documentation',
    'digital',
    'Comprehensive standard operating procedures (SOPs), knowledge bases, and onboarding guides.',
    'Capture critical institutional knowledge into searchable, structured digital documentation that streamlines team training.',
    'FileCode',
    ['Internal Knowledge Base Architecture', 'Step-by-step SOP Creation', 'Notion/Confluence/GitBook Templates', 'Search-indexed Structure'],
    ['Growing Agencies', 'Remote Teams', 'Operations Directors'],
    null,
    null,
    47
  ),
  createServiceObj(
    'Business Documents',
    'business-documents',
    'digital',
    'Bespoke contracts, non-disclosure agreements, scopes of work, and project charter templates.',
    'Protect your operations with well-structured, formatted business documentation ready for execution.',
    'Shield',
    ['SOW & Master Services Templates', 'NDA & Agreement Formats', 'Executive Project Briefs', 'Digital Signature Readiness'],
    ['Startups & Founders', 'Service Agencies', 'Project Managers'],
    null,
    null,
    48
  ),
];

export const sampleProjects = [
  {
    title: 'Aethelgard Capital Management',
    slug: 'aethelgard-capital-management',
    category: 'Technology',
    shortDescription: 'High-frequency asset management portal with real-time portfolio telemetry and algorithmic rebalancing.',
    description: 'Aethelgard needed a unified trading and investor management portal capable of aggregating multi-exchange positions, presenting interactive real-time risk surfaces, and executing automated compliance checks. We architected a custom MERN platform with sub-second WebSocket state distribution and a dark obsidian UI that matches institutional prestige.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    ],
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS', 'Recharts', 'WebSockets'],
    client: 'Aethelgard Global Partners',
    featured: true,
    published: true,
  },
  {
    title: 'Kinetix Autonomous Robotics',
    slug: 'kinetix-autonomous-robotics',
    category: 'Creative',
    shortDescription: 'Brand identity, typography system, and 3D web showcase for an industrial drone robotics firm.',
    description: 'We developed an original visual identity and digital showcase for Kinetix, emphasizing precision engineering through sharp typography, subtle champagne accents, and an interactive fleet telemetry visualization.',
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',
    ],
    technologies: ['Brand Strategy', 'Visual Identity', 'Typography', 'Framer Motion', 'React'],
    client: 'Kinetix Robotics Corp',
    featured: true,
    published: true,
  },
  {
    title: 'Luminary Health Platform',
    slug: 'luminary-health-platform',
    category: 'Technology',
    shortDescription: 'HIPAA-compliant telehealth ecosystem connecting specialized clinicians with global patients.',
    description: 'A comprehensive medical consultation platform featuring encrypted video consultations, real-time doctor scheduling, electronic prescription generation, and automated patient intake pipelines.',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    ],
    technologies: ['React', 'Express.js', 'MongoDB', 'WebRTC', 'Tailwind CSS'],
    client: 'Luminary Health Network',
    featured: true,
    published: true,
  },
  {
    title: 'Vespera Atelier Design Studio',
    slug: 'vespera-atelier-design-studio',
    category: 'Digital',
    shortDescription: 'Digital transformation, NFC business integrations, and automated client intake system.',
    description: 'Vespera required a seamless digital presence upgrade, replacing manual inquiries with smart booking forms, dynamic QR portfolios, and synchronized project tracking.',
    thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    ],
    technologies: ['Digital Cards', 'QR Solutions', 'WhatsApp Business', 'Automated Forms'],
    client: 'Vespera Atelier',
    featured: true,
    published: true,
  },
];

export const defaultVentures = [
  {
    title: 'Project Chronos AI',
    slug: 'project-chronos-ai',
    description: 'Autonomous contextual intelligence engine for enterprise workflows and multi-agent coordination.',
    status: 'Coming Soon',
    tags: ['AI & Core Systems', 'Autonomous Agents'],
    order: 1,
    published: false, // Remains unpublished in public API to strictly respect the secrecy requirement
  },
  {
    title: 'Synapse Data Grid',
    slug: 'synapse-data-grid',
    description: 'Ultra-low-latency distributed data orchestration protocol for real-time edge computing.',
    status: 'Coming Soon',
    tags: ['Distributed Systems', 'Edge Protocol'],
    order: 2,
    published: false, // Strict secrecy
  },
  {
    title: 'Aura Design Engine',
    slug: 'aura-design-engine',
    description: 'Generative interface synthesis tool translating natural language design tokens into production code.',
    status: 'Coming Soon',
    tags: ['Generative UI', 'Design Systems'],
    order: 3,
    published: false, // Strict secrecy
  },
];

export const defaultSettings = {
  companyName: 'Vanguard Digital',
  tagline: "Technology, creativity and digital solutions for what's next.",
  email: 'contact@vanguard-digital.tech',
  phone: '+1 (555) 019-2834',
  whatsapp: '+1 (555) 019-2834',
  instagram: 'https://instagram.com/vanguard.digital',
  linkedin: 'https://linkedin.com/company/vanguard-digital',
  website: 'https://vanguard-digital.tech',
};
